// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutBranch'](arg1, arg2);
}

export function GetCentralInfoDTO() {
  return window['go']['main']['App']['GetCentralInfoDTO']();
}

export function GetGitBranches(arg1) {
  return window['go']['main']['App']['GetGitBranches'](arg1);
}

export function GetRunningProcesses() {
  return window['go']['main']['App']['GetRunningProcesses']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function PickBaseApplicationFolder() {
  return window['go']['main']['App']['PickBaseApplicationFolder']();
}

export function PickCentralInfoFolder() {
  return window['go']['main']['App']['PickCentralInfoFolder']();
}

export function PickGitFolder(arg1) {
  return window['go']['main']['App']['PickGitFolder'](arg1);
}

export function PickJarFile() {
  return window['go']['main']['App']['PickJarFile']();
}

export function RunAll() {
  return window['go']['main']['App']['RunAll']();
}

export function RunApplication(arg1) {
  return window['go']['main']['App']['RunApplication'](arg1);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartLogStreaming(arg1) {
  return window['go']['main']['App']['StartLogStreaming'](arg1);
}

export function StopAllApplications() {
  return window['go']['main']['App']['StopAllApplications']();
}

export function StopApplication(arg1) {
  return window['go']['main']['App']['StopApplication'](arg1);
}

export function StopLogStreaming() {
  return window['go']['main']['App']['StopLogStreaming']();
}
