// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {domain} from '../models';
import {util} from '../models';

export function CheckoutBranch(arg1:string,arg2:string):Promise<void>;

export function GetCentralInfoDTO():Promise<dto.CentralInfoDTO>;

export function GetGitBranches(arg1:string):Promise<domain.Branches>;

export function GetRunningProcesses():Promise<Array<dto.RunningProcessDTO>>;

export function GetSettings():Promise<domain.AppSettings>;

export function PickBaseApplicationFolder():Promise<dto.PickBaseApplicationFolderDTO>;

export function PickCentralInfoFolder():Promise<string>;

export function PickGitFolder(arg1:string):Promise<string>;

export function PickJarFile():Promise<string>;

export function RunAll():Promise<void>;

export function RunApplication(arg1:string):Promise<util.CommandResult>;

export function Save(arg1:domain.CentralInfo):Promise<dto.CentralInfoDTO>;

export function SaveSettings(arg1:domain.AppSettings):Promise<void>;

export function StartLogStreaming(arg1:string):Promise<void>;

export function StopAllApplications():Promise<void>;

export function StopApplication(arg1:string):Promise<void>;

export function StopLogStreaming():Promise<void>;
